from pydantic import BaseModel, Field
from typing import Optional, List

class UserIntent(BaseModel):
    category: str = Field(description="The category of food, e.g., 'biryani', 'pizza'")
    diet: Optional[str] = Field(None, description="'veg' or 'non-veg' or None")
    budget: Optional[float] = Field(None, description="The maximum price in INR")
    location: Optional[str] = Field(None, description="The user's location or 'near me'")
    task_type: str = Field(description="'Discovery' for general deals, 'Search' for specific item")
    agent_goal: Optional[str] = Field(None, description="A highly specific TinyFish prompt generated by LLaMA.")
    preferred_platforms: List[str] = Field(default_factory=list, description="List of preferred platforms")

class DealItem(BaseModel):
    platform: str = Field(description="'Swiggy' or 'Zomato'")
    restaurant_name: str
    item_name: str
    price: float
    delivery_fee: float = 0.0
    discount: float = 0.0
    true_price: float = 0.0
    rating: float = 0.0
    item_url: str
